Fiap.Apostila07.MVC.Web/Fiap.Apostila07.MVC.Web/Models/Aluno.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fiap.Apostila07.MVC.Web.Models
{
    public class Aluno
    {
        [Key]
        public int Rm { get; set; }
        public string Nome { get; set; }

        //Relacionamento bidirecional
        public GrupoAm GrupoAm { get; set; }
        public int GrupoAmId { get; set; }

        //Relacionamento Many-To-Many
        public virtual List<Professor> Professores { get; set; }
    }
}

Fiap.Apostila07.MVC.Web/Fiap.Apostila07.MVC.Web/Models/GrupoAm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap.Apostila07.MVC.Web.Models
{
    public class GrupoAm
    {
        public int GrupoAmId { get; set; }
        public string Nome { get; set; }

        //Relacionamento one-to-one
        public ProjetoAm Projeto { get; set; }
        public int ProjetoAmId { get; set; }

        //Relacionamento one-to-many
        public virtual List<Aluno> Alunos { get; set; }
    }
}

Fiap.Apostila07.MVC.Web/Fiap.Apostila07.MVC.Web/Models/Professor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fiap.Apostila07.MVC.Web.Models
{
    public class Professor
    {
        [Key]
        public int Pf { get; set; }
        public string Nome { get; set; }

        //Relacionamento Many-To-Many
        public virtual List<Aluno> Alunos { get; set; }
    }
}

Fiap.Apostila07.MVC.Web/Fiap.Apostila07.MVC.Web/Models/ProjetoAm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fiap.Apostila07.MVC.Web.Models
{
    public class ProjetoAm
    {
        public int ProjetoAmId { get; set; }

        [Display(Name = "Título")]
        public string Titulo { get; set; }

        public string Tema { get; set; }

        [Display(Name ="Data de Entrega")]
        public DateTime DataEntrega { get; set; }
    }
}

Fiap.Apostila07.MVC.Web/Fiap.Apostila07.MVC.Web/Controllers/AlunoController.cs
using Fiap.Apostila07.MVC.Web.Contexts;
using Fiap.Apostila07.MVC.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Apostila07.MVC.Web.Controllers
{
    public class AlunoController : Controller
    {
        private AmContext _context = new AmContext();

        //Busca por Grupo de AM
        public ActionResult Buscar(int codigo)
        {
            //Filtra a lista de alunos
            var lista = _context.Alunos.Include("GrupoAm").Where(a => a.GrupoAmId == codigo).ToList();
            //Carrega as opções do Select
            var grupos = _context.Grupos.ToList();
            ViewBag.opcoes = new SelectList(grupos, "GrupoAmId", "Nome");
            //Retorna para a Listar.cshtml com a lista filtrada
            return View("Listar",lista);
        }

        [HttpGet]
        public ActionResult Listar()
        {
            var grupos = _context.Grupos.ToList();
            ViewBag.opcoes = new SelectList(grupos, "GrupoAmId", "Nome");
            var alunos = _context.Alunos.Include("GrupoAm").ToList();
            return View(alunos);
        }

        //Cadastrar um aluno
        [HttpGet]
        public ActionResult Cadastrar()
        {
            //Buscar todos os grupos cadastrados
            var grupos = _context.Grupos.ToList();
            //Manda para a tela as informações para montar o select
            ViewBag.opcoes = new SelectList(grupos,"GrupoAmId","Nome");
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Aluno aluno)
        {
            _context.Alunos.Add(aluno);
            _context.SaveChanges();
            TempData["msg"] = "Aluno cadastrado";
            return Redirect("Cadastrar");
        }
    }
}

Fiap.Apostila07.MVC.Web/Fiap.Apostila07.MVC.Web/Controllers/GrupoController.cs
using Fiap.Apostila07.MVC.Web.Contexts;
using Fiap.Apostila07.MVC.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Apostila07.MVC.Web.Controllers
{
    public class GrupoController : Controller
    {
        private AmContext _context = new AmContext();

        [HttpGet]
        public ActionResult Listar()
        {
            //Preenche também a propriedade Projeto do Grupo
            var listaGrupos = _context.Grupos.Include("Projeto").ToList();
            return View(listaGrupos);
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(GrupoAm grupo)
        {
            _context.Grupos.Add(grupo);
            _context.SaveChanges();
            TempData["msg"] = "Grupo registrado!";
            return View();
        }
    }
}

Fiap.Apostila07.MVC.Web/Fiap.Apostila07.MVC.Web/Views/Aluno/Cadastrar.cshtml
@model Fiap.Apostila07.MVC.Web.Models.Aluno
@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastro de aluno</h2>
@if (TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(a => a.Nome)
        @Html.TextBoxFor(a => a.Nome, new { @class = "form-control"})
    </div>
    <div class="form-group">
        @Html.LabelFor(a => a.GrupoAm)
        @Html.DropDownListFor(a => a.GrupoAmId, ViewBag.opcoes as SelectList,
                                            "Selecione", new { @class = "form-control" })
    </div>
    <div class="form-group">
        <input type="submit" value="Salvar" class="btn btn-primary" />
    </div>
}

Fiap.Apostila07.MVC.Web/Fiap.Apostila07.MVC.Web/Views/Aluno/Listar.cshtml
@model List<Fiap.Apostila07.MVC.Web.Models.Aluno>
@{
    ViewBag.Title = "Listar";
}

<h2>Alunos Registrados</h2>

@using (Html.BeginForm("Buscar", "Aluno", FormMethod.Get, new { @class = "form-inline", id = "formulario" }))
{ 
    @Html.DropDownList("Codigo", ViewBag.opcoes as SelectList, new { @class = "form-control" , onchange = "formulario.submit()" })
    <input type="submit" value="Buscar" class="btn btn-success"/>
}
<hr />
<table class="table table-striped">
    <tr>
        <th>Nome</th>
        <th>Grupo</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Nome</td>
            <td>@item.GrupoAm.Nome</td>
        </tr>
    }
</table>

Fiap.Apostila07.MVC.Web/Fiap.Apostila07.MVC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FIAP AM</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FIAP AM", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cadastro de Grupo","Cadastrar","Grupo")</li>
                    <li>@Html.ActionLink("Grupos","Listar","Grupo")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Alunos <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastro","Cadastrar","Aluno")</li>
                            <li>@Html.ActionLink("Lista","Listar","Aluno")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - FIAP AM</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>